#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Function to run linting for a directory
run_lint() {
  local directory="$1"
  echo "Linting the $directory..."
  (cd "$directory" && npm run test) # Replace with the actual linting command for the directory
}

# Check if there are changes in the backend or frontend
check_changes() {
  local relative_path="$1"
  if git diff --cached --name-only --exit-code --relative="$relative_path" >/dev/null; then
    run_lint "$relative_path"
  fi
}

check_changes "backend"
check_changes "frontend"