#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Function for formatting a directory
format_directory() {
  local dir="$1"
  echo "Formatting $dir..."
  (cd "$dir" && npm run format)
}

# Check the changed files
changed_files=$(git diff --cached --name-only --diff-filter=ACM)

# Array of directories to format
directories_to_format=("frontend" "backend")

# Iterate over directories and format them if there are changes
for dir in "${directories_to_format[@]}"; do
  if echo "$changed_files" | grep -q "^$dir/"; then
    format_directory "$dir"
  fi
done

# Continue the commit if formatting is successful
exit 0
